import React from 'react'
import { graphql } from 'gatsby'

import PageHeader from '../components/PageHeader'
import Content from '../components/Content'
import Layout from '../components/Layout'
import gas_emissions from '../../images/gas_emissions.png'

// Export Template for use in CMS preview
export const HomePageTemplate = ({ title, subtitle, featuredImage, body }) => (
  <main className="Home">
    <PageHeader
      large
      title={title}
      subtitle={subtitle}
      backgroundImage={featuredImage}
    />

    <section className="section">
      <div className="container">
        <Content source={body} />
          <center>
            <a href="/quiz">
              <div className="Button" tabindex="0" aria-label="Toggle Popup" role="button">Take a Preference Quiz</div>
            </a>
            <div className="Divider"/>
            <a href="/news">
            <div className="Button" tabindex="0" aria-label="Toggle Popup" role="button">Learn More about Electric Vehicles</div>
            </a>
          </center>
      </div>
      <div className="Divider"/>
      <div className="container">
        <h1>Why Purchase an Electric Vehicle?</h1>
        <h3>Electric Vehicles will be the future of transportation.</h3>
        <p>
          Electric vehicles are inevitably the mode of transportation of the future, since current fossil fuel alternatives are not sustainable, and harmful to the environment.
          Many organizations are taking action to mandate this transition
          (e.g. <a href="https://www.gov.ca.gov/2020/09/23/governor-newsom-announces-california-will-phase-out-gasoline-powered-cars-drastically-reduce-demand-for-fossil-fuel-in-californias-fight-against-climate-change/">
          California governor Gavin Newsom issued an executive order requiring vehicle sales to be entirely emission free by 2035</a>).
        </p>
        
        <h3>Electric Vehicles are better for the environment.</h3>
        <p>
          While conventional gas cars require petroleum as their sole source of fuel, electric vehicles use electricity, which can be generated by renewable sources of energy,
          such as wind and the sun (which are all carbon neutral).
        </p>

        <h3>Isn't electricity produced from sources that produce carbon?</h3>
        <p>
          It is true that the source of electricity does stem from polluting sources, however, electric vehicles create flexibility in the choice between these polluting options
          and renewable sources, while this flexibility does not exist with gas vehicles. If we were to stick with gas vehicles, there would be no opportunity to transition to
          a cleaner and more sustainable future.
        </p>

        <h3>Isn't the production of electric vehicles more harmful to the environment than gas vehicles?</h3>
        <p>
          Although carbon footprint of the initial production of an electric vehicle may be larger than its gas vehicle equivalent, the overall lifetime carbon footprint 
          of the electric vehicle is still substantially better. For reference, the following figure (<a href="https://www.carbonbrief.org/factcheck-how-electric-vehicles-help-to-tackle-climate-change">source</a>)
          shows the overall carbon emissions produced throughout the lifecycle of a typical European gas car, a hybrid Toyota Prius Eco, and an all-electric Nissan Leaf.
        </p>
        <img src={gas_emissions} class="center"></img>

      </div>
    </section>
  </main>
)

// Export Default HomePage for front-end
const HomePage = ({ data: { page } }) => (
  <Layout meta={page.frontmatter.meta || false}>
    <HomePageTemplate {...page} {...page.frontmatter} body={page.html} />
  </Layout>
)

export default HomePage

export const pageQuery = graphql`
  ## Query for HomePage data
  ## Use GraphiQL interface (http://localhost:8000/___graphql)
  ## $id is processed via gatsby-node.js
  ## query name must be unique to this file
  query HomePage($id: String!) {
    page: markdownRemark(id: { eq: $id }) {
      ...Meta
      html
      frontmatter {
        title
        subtitle
        featuredImage
      }
    }
  }
`
